<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="4" time="0.891" timestamp="2023-07-08T22:51:01.792799" hostname="18091b2ad511"><testcase classname="" name="tests.application.useCases.test_RelatorioUseCase" time="0.000"><error message="collection failure">ImportError while importing test module '/app/tests/application/useCases/test_RelatorioUseCase.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/application/useCases/test_RelatorioUseCase.py:6: in &lt;module&gt;
    from mock_alchemy.mocking import UnifiedAlchemyMagicMock
E   ModuleNotFoundError: No module named 'mock_alchemy'</error></testcase><testcase classname="tests.domain.repositories.test_centro_repository" name="test_save_new_centro" time="0.026" /><testcase classname="tests.domain.repositories.test_centro_repository" name="test_invalidateCentro" time="0.005" /><testcase classname="tests.domain.repositories.test_centro_repository" name="test_validateCentro" time="0.009" /></testsuite></testsuites>